### ISSUE TITLE
@Auth注解问题，在AuthMethodArgumentResolver中，@Autowired不起作用

### ISSUE THREAD

**Issue by yiicode101** [ocubexo/springboot-restful-starter#1]
访问/auth路径，在AuthMethodArgumentResolver中，@Autowired不起作用，导致tokenService服务类加载为NULL，如果手动创建TokenService对象，此时TokenService实例中的 @Value注解获取不到值
![image](https://user-images.githubusercontent.com/12236279/50499483-e70f2100-0a84-11e9-8220-02da6816652b.png)

已赞助
方便加微信吗？

**Comment by lmarklil** [comment]
感谢支持，最近很忙所以没有上来看，很抱歉。我的微信号是ocubexo，我测试的时候并没有这个问题，你使用的java版本是多少？

**Comment by lmarklil** [comment]
项目现在已经更新，你可以试一下之前的问题还存不存在。

**Comment by yumifen** [comment]
refresh_token是不是没用上，用户一直操作access_token失效的咋办？
