### ISSUE TITLE
refresh_token是不是没用上，用户一直操作access_token失效的咋办？

### ISSUE THREAD

**Issue by yumifen** [ocubexo/springboot-restful-starter#2]

**Comment by lmarklil** [comment]
refreshToken是用来刷新accessToken的，这个应该由前端判断，当accessToken过期时自动访问token刷新接口来获取新的accessToken。

**Comment by zwdgit** [comment]
> refreshToken是用来刷新accessToken的，这个应该由前端判断，当accessToken过期时自动访问token刷新接口来获取新的accessToken。

请问目前项目还没有提供 token刷新接口 是吗？
